name: terraform-plan

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - run: terraform init
      - run: terraform plan -lock=false -out terraform.plan
       # generate json output
      - run: terraform show -json terraform.plan > terraform.json
